title: Matthew Feil
author:
  name: Matthew Feil

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  The website of Matthew Feil, a high school student with a passion for music and technology.

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag

date_format: "%b %-d, %Y"

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false
