const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = vm.createContext({ structuredClone, crypto: require('node:crypto').webcrypto });
vm.runInContext(fs.readFileSync('assets/js/transcribe-marks.js','utf8'),ctx);
const { Marks, rows, validate } = ctx.TranscribeMarks;
const doc = { numbering:'section', markers:[{id:'c',time:8,section:true},{id:'a',time:0,section:true},{id:'b',time:4,section:false},{id:'d',time:12,section:false}] };
const labels = d => Array.from(rows(d),m=>m.label);
assert.deepEqual(labels(doc),['A1','A2','B1','B2']);
assert.deepEqual(labels({...doc,numbering:'continuous'}),['A1','A2','B3','B4']);
assert.equal(rows({numbering:'section',markers:Array.from({length:28},(_,i)=>({id:String(i),time:i,section:true}))})[27].label,'AB1');
let now=1, loop;
const model = Object.create(Marks.prototype);
Object.assign(model,{doc:{markers:[],numbering:'section'},ready:true,undoStack:[],redoStack:[],host:{current:()=>now,duration:()=>20,seek:t=>now=t,loop:(a,b)=>loop=[a,b]},refresh(){},save(){},say(){}});
model.mark(false); assert.equal(model.doc.markers[0].section,true);
now=1.04; model.mark(true); assert.equal(model.doc.markers.length,1);
now=5; model.mark(false); now=9; model.mark(true); now=13; model.mark(false);
assert.deepEqual(labels(model.doc),['A1','A2','B1','B2']);
now=6; model.loop(false); assert.deepEqual(loop,[5,9]);
model.loop(true); assert.deepEqual(loop,[1,9]);
now=14; model.loop(true); assert.deepEqual(loop,[9,20]);
model.navigate(-1); assert.equal(now,13); model.navigate(-1,true); assert.equal(now,9);
model.remove(); assert.equal(model.doc.markers.length,3); model.history(false); assert.equal(model.doc.markers.length,4); model.history(true); assert.equal(model.doc.markers.length,3);
const event = {key:'m',preventDefault(){},repeat:true}; const count=model.doc.markers.length; now=17;model.key(event);assert.equal(model.doc.markers.length,count);
model.key({...event,repeat:false});assert.equal(model.doc.markers.length,count+1);
assert.throws(()=>validate({version:1,identity:'wrong',...doc},'file',20));
assert.throws(()=>validate({version:1,identity:'file',...doc,markers:[{id:'x',time:99,section:false}]},'file',20));
assert.throws(()=>validate({version:1,identity:'file',...doc,markers:[{id:'x',time:1,section:false},{id:'y',time:1,section:false}]},'file',20));
assert.deepEqual(labels(validate({version:1,identity:'file',...doc},'file',20)),['A1','A2','B1','B2']);
console.log('Marker numbering, capture, history, navigation, loops, and validation passed.');
